### PR TITLE
Use file.bytes()

### PR DESCRIPTION
**Pull request by 7heMech**

### CODE REVIEW

**Review by mavyfaby — APPROVED** [review]
LGTM! Thanks for contributing your first pull request. Let's work together to make this library even better.

**Comment by 7heMech** [comment]
@mavyfaby you know, I don't really like libraries being sync by default since it hangs the main thread, but there are also performance trade-offs as per the `fflate` docs:
> As you may have guessed, there is an asynchronous version of every method as well. Unlike most libraries, this will cause the compression or decompression run in a separate thread entirely and automatically by using Web (or Node) Workers. This means that the processing will not block the main thread at all.

> Note that there is a significant initial overhead to using workers of about 50ms for each asynchronous function. For instance, if you call unzip ten times, the overhead only applies for the first call, but if you call unzip and zlib, they will each cause the 50ms delay. For small (under about 50kB) payloads, the asynchronous APIs will be much slower. However, if you're compressing larger files/multiple files at once, or if the synchronous API causes the main thread to hang for too long, the callback APIs are an order of magnitude better.

**Comment by mavyfaby** [comment]
@7heMech what can you suggest?

**Comment by 7heMech** [comment]
> @7heMech what can you suggest?

I was thinking maybe explaining that in package docs and let the user pass working mode as a parameter.

**Comment by 7heMech** [comment]
That or we can just go full async and take the 50ms hit on the first file which isn't that much.

**Comment by mavyfaby** [comment]
that'll do, I'll add documentation first.

**Comment by 7heMech** [comment]
> that'll do, I'll add documentation first.

Yeah, or you can export two:
Async and not

**Pull request merged**
